//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by shendenkov23 templates
//

import UIKit

class ___VARIABLE_moduleName___ViewController: UITableViewController {
  var presenter: ___VARIABLE_moduleName___Presenter?
  
  // MARK: -
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
}

// MARK: - ___VARIABLE_moduleName___View

extension ___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___View {
  
}
