//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by shendenkov23 templates
//

import UIKit

class ___VARIABLE_moduleName___RouterImplementation {
  weak var view: ___VARIABLE_moduleName___View?
  
  // MARK: -
  
  init(view: ___VARIABLE_moduleName___View) {
    self.view = view
  }
}

// MARK: - ___VARIABLE_moduleName___Router

extension ___VARIABLE_moduleName___RouterImplementation: ___VARIABLE_moduleName___Router {
  
}
