//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by shendenkov23 templates
//

import UIKit

class ___VARIABLE_moduleName___Configurator {
  static func configure(_ view: ___VARIABLE_moduleName___ViewController) {
    let router = ___VARIABLE_moduleName___RouterImplementation(view: view)
    let presenter = ___VARIABLE_moduleName___PresenterImplementation(view: view, router: router)
    
    view.presenter = presenter
  }
}
