//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by shendenkov23 templates
//

import UIKit

protocol ___VARIABLE_moduleName___Router {
  
}

protocol ___VARIABLE_moduleName___View: class {

}

protocol ___VARIABLE_moduleName___Presenter {
  
}

class ___VARIABLE_moduleName___PresenterImplementation {
  private weak var view: ___VARIABLE_moduleName___View?
  private let router: ___VARIABLE_moduleName___Router
  
  // MARK: -
  
  init(view: ___VARIABLE_moduleName___View, router: ___VARIABLE_moduleName___Router) {
    self.view = view
    self.router = router
  }
}

// MARK: - ___VARIABLE_moduleName___Presenter

extension ___VARIABLE_moduleName___PresenterImplementation: ___VARIABLE_moduleName___Presenter {
  
}
